A = rand(100);
x = eig(A);
figure(1);
scatter(1:100, sort(abs(x)), 'x');
xlabel('i');
ylabel('|\lambda_i|');
figure(2);
plot(real(x), imag(x), 's');
hold on;
[Q, S] = Q1(A, rand(100,1), 1);
plot(real(S), imag(S), '^');
hold on;
[Q, S] = Q1(A, rand(100,1), 2);
y = eig(S);
plot(real(y), imag(y), '*');
hold on;
[Q, S] = Q1(A, rand(100,1), 3);
y = eig(S);
plot(real(y), imag(y), 'p');
hold off;
legend('eig(A)', 'Arnoldi, n=1', 'Arnoldi, n=2', 'Arnoldi, n=3');
axis([0, 60, -Inf, Inf]);
xlabel('Re(\lambda_i)');
ylabel('Im(\lambda_i)');
